services:
  - type: web
    name: ai-skin-disease-backend
    env: node
    buildCommand: "npm install && pip install --no-cache-dir -r requirements.txt"
    startCommand: "npm start"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
